version: '3'
services:
  wp:
    build: .
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_PASSWORD: trustno1
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: trustno1
    volumes:
          - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume: